# GitLab Repository Management Tool Configuration
# Copy this file to config.yml and customize it for your needs

gitlab:
  url: "https://gitlab.com"
  private_token: "your-gitlab-token-here"

github:
  url: "https://api.github.com"
  access_token: "your-github-token-here"

repository:
  repo_dir: "."  # Current working directory
  max_concurrent_downloads: 5

groups:
  target_group_ids:
    - 2969050   # circlecreative
    - 60830364  # circle-creative-flutter
    - 12276251  # church-id
    - 7629247   # kreditimpian-id
    - 6443630   # itsynergy
    - 4939058   # pluses-media
    - 2987114   # o2system
    - 2968903   # baliparamartha
    - 108468311 # x-api
    - 110485899 # neo
    - 60815546  # sendx
    - 60815062  # motoriz
    - 60789937  # cicilsewa
    - 60789934  # tokobot
    - 14193703  # xignature
    - 13844839  # simplex
    - 13844814  # Lawtify

composer:
  enabled: true
  auto_update: false  # Set to true to automatically update after cloning 